### ISSUE TITLE
How to simply push code

### ISSUE THREAD

**Issue by ThePurpleOne** [essele/pico_debug#10]
From what i can gather from the readme, it's possible to push code without any openOCD stuff. But beside the vscode setup, i don't get how we are suppose to flash the other RP2040.

What should i use if I only wanted to flash it, by hand, from cli tools ?

**Comment by essele** [comment]
Hi,

This tool isn't really designed to be used from the command-line, it's used from within GDB (which is kicked of by VSCode in most cases) ... you could probably script something to work with GDB, but it's not something I've tried.

I can see a use-case for bulk programming where a command-line would be really useful, but unfortunately I'm not working on this at the moment (I will come back to it, especially given the new devices), but I'm in the middle of something else for the next few months.

Lee.
