### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by rgrr** [essele/pico_debug#3]
Hello Lee,

actually not an issue... I'm wondering under what license your sources are?

I'm currently thinking about extending picoprobe with a mass storage device which writes to the probe target.  Just like the boot code does but with the probe in between.  Based on your findings, this should increase upload speed by at least a magnitude compared to CMSIS-DAP.

flash.c seems to contain some code of interest ;-)  actually not very much code, but a very good starter (and I guess a lot of fiddling til it did what it was supposed to do).

Regards
Hardy

**Comment by essele** [comment]
Hi,

I've used the MIT license as I don't mind what you do with the code ... I did this for my own benefit and for the fun and experience, there's nothing proprietary or particularly clever in there, in fact I wouldn't have been able to get anywhere close without the benefit of other open source examples!

Unfortunately I've been busy with other things so haven't had any time to continue to develop this, I did have some ideas including some dedicated hardware ... but I suspect that will have to wait a while!

So, as far as the code goes, feel free to use/reuse any of it.

Cheers,

Lee.
