### ISSUE TITLE
If you're looking for Ethernet on the Pico

### ISSUE THREAD

**Issue by holysnippet** [essele/pico_debug#6]
Hello, I came across your project, which seems promising. I've read a bit of the documentation. If you want to implement Ethernet in addition to Wifi and Usb/CDC you could take a look at my Git repository:
https://github.com/holysnippet/pico_eth_doc 
It's an implementation of 10M Ethernet on the Pico thanks to the PIO.

**Comment by essele** [comment]
Hi ... thanks for the comments on the project.

As far as ethernet goes I suspect I'm a little ahead of you ... here is my 10/100 implementation, needs a bit of a tweak if you want to use it on the PICO, it's really meant to work in custom RP2040 projects. I use it in a couple of things.

https://github.com/essele/rp2040-rmii

Lee.

**Comment by holysnippet** [comment]
Hello, thank you for your reply. I took a look at your Ethernet implementation. You need a transceiver and a transformer. My implementation only needs an Ethernet transformer and some passives! But it's only 10Mb/s. On the other hand, like yours, it provides lwIp!

Oh yes, I forgot, I'm working with your excellent probe! It's really great for both uploading and debugging. It's really a great job! I no longer have to wait dozens of seconds for each compilation/upload. Thank you so much!
